// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const MYSQL_URL = import.meta.env.VITE_MYSQL_URL;
const MYSQL_PUBLISHABLE_KEY = import.meta.env.VITE_MYSQL_PUBLISHABLE_KEY;

// Import the mysql client like this:
// import { mysql } from "@/integrations/mysql/client";

export const mysql = createClient<Database>(MYSQL_URL, MYSQL_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
