import { serve } from "https://deno.land/std@0.168.0/http/server.ts"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { summary, monthlyData, generatedBy, generatedAt } = await req.json();

    // Create detailed treasurer report in CSV format
    const csvContent = [
      '"TNS TREASURER REPORT"',
      `"Generated By: ${generatedBy}"`,
      `"Generated On: ${new Date(generatedAt).toLocaleString()}"`,
      '',
      '"FINANCIAL SUMMARY"',
      '"Metric","Amount (KES)"',
      `"Total Active Members","${summary.totalMembers}"`,
      `"Total Contributions Received","${summary.totalContributions.toLocaleString()}"`,
      `"Total Disbursements Made","${summary.totalDisbursements.toLocaleString()}"`,
      `"Monthly Operating Expenses","${summary.monthlyExpenses.toLocaleString()}"`,
      `"Current Net Position","${summary.netPosition.toLocaleString()}"`,
      `"Average Monthly Contribution","${summary.avgMonthlyContribution.toLocaleString()}"`,
      `"Average Disbursement Amount","${summary.avgDisbursement.toLocaleString()}"`,
      '',
      '"MONTHLY FINANCIAL TRENDS"',
      '"Month","Active Members","Contributions (KES)","Disbursements (KES)","Expenses (KES)","Net Position (KES)","Growth %"',
      ...monthlyData.map((data: any) => {
        const net = data.contributions - data.disbursements - data.expenses;
        const growth = data.growth ? `${data.growth.toFixed(2)}%` : '0.00%';
        return `"${data.month}","${data.members}","${data.contributions.toLocaleString()}","${data.disbursements.toLocaleString()}","${data.expenses.toLocaleString()}","${net.toLocaleString()}","${growth}"`;
      }),
      '',
      '"FINANCIAL HEALTH INDICATORS"',
      '"Indicator","Value","Status"',
      `"Contribution Growth Rate","${summary.contributionGrowth?.toFixed(2) || 0}%","${summary.contributionGrowth > 5 ? 'Good' : summary.contributionGrowth > 0 ? 'Fair' : 'Needs Attention'}"`,
      `"Expense Ratio","${summary.expenseRatio?.toFixed(2) || 0}%","${summary.expenseRatio < 15 ? 'Good' : summary.expenseRatio < 25 ? 'Fair' : 'High'}"`,
      `"Liquidity Position","${summary.liquidityRatio?.toFixed(2) || 0}","${summary.liquidityRatio > 2 ? 'Excellent' : summary.liquidityRatio > 1 ? 'Good' : 'Low'}"`,
      '',
      '"RECOMMENDATIONS"',
      `"- ${summary.netPosition >= 0 ? 'Maintain current positive financial position' : 'Urgent: Address negative financial position'}"`,
      `"- ${summary.contributionGrowth > 0 ? 'Continue encouraging member contributions' : 'Focus on increasing member participation and contributions'}"`,
      `"- ${summary.expenseRatio < 20 ? 'Operating expenses are well controlled' : 'Review and optimize operating expenses'}"`,
      '"- Consider diversifying revenue streams for long-term sustainability"',
      '"- Implement regular financial monitoring and reporting systems"',
      '',
      '"REPORT NOTES"',
      '"- All amounts are in Kenya Shillings (KES)"',
      '"- Data includes all approved members and verified transactions"',
      '"- Monthly trends help identify seasonal patterns and cash flow"',
      '"- Financial health indicators are based on industry standards"',
      '"- This report should be reviewed monthly for effective financial management"',
      '',
      '"END OF TREASURER REPORT"'
    ].join('\n');

    return new Response(csvContent, {
      headers: {
        ...corsHeaders,
        'Content-Type': 'text/csv',
        'Content-Disposition': `attachment; filename="TNS_Treasurer_Report_${new Date().toISOString().split('T')[0]}.csv"`
      }
    });

  } catch (error) {
    console.error('Error generating treasurer report:', error);
    return new Response(
      JSON.stringify({ error: 'Failed to generate treasurer report' }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }, 
        status: 500 
      }
    );
  }
});